"""
lexicons.py
===========
Reference data for the NLP Lyrics Analyzer.

Everything here is *pure data*: dictionaries that map a surface form (what a
learner actually reads in the lyrics) to a plain-English explanation.
The matching logic lives in `nlp_engine.py`.

Five pedagogical categories are used across the app:

    Contraction    -> standard written English (he's, don't, we'll)
    Reduced Form   -> informal / spoken-only spellings (gonna, comin', 'cause)
    Phrasal Verb   -> verb + particle whose meaning is not literal (give up)
    Idiom          -> fixed figurative expression (break my heart)
    Slang          -> informal vocabulary, often generational (lit, flex)

Splitting "Contraction" from "Reduced Form" matters for learners: `he's` is
correct in an essay, `he's comin'` is not.
"""

# ==========================================================================
# 1. STANDARD CONTRACTIONS
#    Correct written English. Keys are lowercase; matching is case-insensitive.
# ==========================================================================
STANDARD_CONTRACTIONS = {
    # --- to be / to have / will / would with pronouns -------------------
    "i'm": "I am",
    "i've": "I have",
    "i'll": "I will",
    "i'd": "I would / I had",
    "you're": "you are",
    "you've": "you have",
    "you'll": "you will",
    "you'd": "you would / you had",
    "he's": "he is / he has",
    "he'll": "he will",
    "he'd": "he would / he had",
    "she's": "she is / she has",
    "she'll": "she will",
    "she'd": "she would / she had",
    "it's": "it is / it has",
    "it'll": "it will",
    "it'd": "it would / it had",
    "we're": "we are",
    "we've": "we have",
    "we'll": "we will",
    "we'd": "we would / we had",
    "they're": "they are",
    "they've": "they have",
    "they'll": "they will",
    "they'd": "they would / they had",

    # --- demonstratives, existentials, question words -------------------
    "that's": "that is / that has",
    "that'll": "that will",
    "that'd": "that would",
    "there's": "there is / there has",
    "there're": "there are",
    "there'll": "there will",
    "there'd": "there would",
    "here's": "here is",
    "who's": "who is / who has",
    "who're": "who are",
    "who've": "who have",
    "who'll": "who will",
    "who'd": "who would / who had",
    "what's": "what is / what has",
    "what're": "what are",
    "what'll": "what will",
    "what'd": "what did / what would",
    "where's": "where is",
    "where're": "where are",
    "where'd": "where did / where would",
    "where'll": "where will",
    "when's": "when is",
    "when'd": "when did",
    "why's": "why is",
    "why'd": "why did / why would",
    "how's": "how is",
    "how'd": "how did / how would",
    "how'll": "how will",
    "let's": "let us",
    "one's": "one is / one has",
    "someone's": "someone is / someone has",
    "somebody's": "somebody is / somebody has",
    "something's": "something is / something has",
    "nobody's": "nobody is / nobody has",
    "nothing's": "nothing is / nothing has",
    "everybody's": "everybody is / everybody has",
    "everyone's": "everyone is / everyone has",
    "everything's": "everything is / everything has",
    "life's": "life is",
    "love's": "love is",
    "night's": "night is",

    # --- negatives -------------------------------------------------------
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "can't": "cannot",
    "couldn't": "could not",
    "won't": "will not",
    "wouldn't": "would not",
    "shouldn't": "should not",
    "shan't": "shall not",
    "mustn't": "must not",
    "mightn't": "might not",
    "needn't": "need not",
    "daren't": "dare not",
    "haven't": "have not",
    "hasn't": "has not",
    "hadn't": "had not",
    "ain't": "am not / is not / are not / has not / have not "
             "(non-standard, very common in songs)",

    # --- fossilised contractions ----------------------------------------
    "o'clock": "of the clock",
    "ma'am": "madam",
}

# ==========================================================================
# 2. REDUCED / INFORMAL FORMS
#    Understand them, but do NOT write them in a formal text.
# ==========================================================================
REDUCED_FORMS = {
    # --- verb + to / of reductions --------------------------------------
    "gonna": "going to (future intention)",
    "gon'": "going to (future intention)",
    "wanna": "want to / want a",
    "gotta": "(have) got to = must",
    "gimme": "give me",
    "lemme": "let me",
    "kinda": "kind of = a little / somewhat",
    "sorta": "sort of = a little / somewhat",
    "outta": "out of",
    "lotta": "lot of",
    "lotsa": "lots of",
    "oughta": "ought to = should",
    "hafta": "have to = must",
    "tryna": "trying to",
    "finna": "fixing to = about to (US Southern / AAVE)",
    "imma": "I'm going to (I am going to)",
    "ima": "I'm going to (I am going to)",
    "dunno": "do not know",
    "gotcha": "got you = I understand / I caught you",
    "gotchu": "got you = I've got your back",
    "betcha": "bet you",
    "whatcha": "what are you / what do you",
    "wanna-be": "someone who imitates what they want to be",

    # --- apostrophe-initial clippings ------------------------------------
    "'cause": "because",
    "'coz": "because",
    "'em": "them",
    "'im": "him",
    "'er": "her",
    "'til": "until",
    "'till": "until",
    "'bout": "about",
    "'round": "around",
    "'fore": "before",
    "'nother": "another",
    "'nuff": "enough",
    "'neath": "beneath",
    "'gainst": "against",
    "'tis": "it is (poetic / archaic)",
    "'twas": "it was (poetic / archaic)",
    "'sup": "what's up? = hello / what is happening?",

    # --- other common spoken spellings -----------------------------------
    "y'all": "you all (plural 'you', US Southern)",
    "ya'll": "you all (common misspelling of y'all)",
    "y'know": "you know",
    "c'mon": "come on",
    "cmon": "come on",
    "s'posed": "supposed",
    "an'": "and",
    "ol'": "old",
    "lil'": "little",
    "lil": "little",
    "til": "until",
    "cuz": "because",
    "coz": "because",
    "cos": "because",
    "innit": "isn't it? (British tag question)",
    "wassup": "what's up? = hello",
    "whassup": "what's up? = hello",
    "nah": "no (informal)",
    "yep": "yes (informal)",
    "nope": "no (informal)",
    "ya": "you (informal, unstressed)",
}

# ==========================================================================
# 3. PHRASAL VERBS
#    Keys are "<verb lemma> <particle>" so that came back / coming back /
#    comes back all resolve to "come back".
# ==========================================================================
PHRASAL_VERBS = {
    # back / down / up with high-frequency verbs
    "back down": "To stop defending an opinion; to withdraw from a fight.",
    "back off": "To move away; to stop pressuring someone.",
    "back up": "To support someone; to move backwards.",
    "blow away": "To impress someone enormously.",
    "blow up": "To explode; to become suddenly famous or very angry.",
    "break away": "To escape from a group or a situation.",
    "break down": "To lose emotional control and cry; to stop functioning.",
    "break out": "To escape; to start suddenly (a fire, a fight).",
    "break through": "To finally overcome an obstacle.",
    "break up": "To end a romantic relationship; to split into pieces.",
    "bring back": "To return something; to make you remember the past.",
    "bring down": "To make someone sad; to cause something to fail.",
    "bring out": "To reveal a quality; to release a product.",
    "bring up": "To raise a subject; to raise a child.",
    "burn out": "To become exhausted after working or feeling too intensely.",
    "call off": "To cancel.",
    "call out": "To publicly criticise someone; to shout to someone.",
    "calm down": "To become less angry or less upset.",
    "carry on": "To continue despite difficulty.",
    "carry out": "To perform or complete a task.",
    "catch up": "To reach the same level as someone; to exchange news.",
    "cheer up": "To become or make someone happier.",
    "chill out": "To relax; to stop worrying.",
    "come across": "To find by chance; to give a certain impression.",
    "come along": "To accompany someone; to make progress.",
    "come around": "To change your mind; to visit someone.",
    "come back": "To return.",
    "come down": "To descend; to lose intensity or status.",
    "come in": "To enter.",
    "come on": "Hurry up / please (encouragement); to start working.",
    "come out": "To be revealed or released; to reveal one's identity.",
    "come over": "To visit someone's home; to affect someone suddenly.",
    "come through": "To succeed when someone depends on you.",
    "come up": "To be mentioned; to happen unexpectedly.",
    "count on": "To rely on / to trust someone.",
    "cut off": "To interrupt; to isolate; to stop a supply.",
    "cut out": "To remove; to stop doing something.",
    "die down": "To become gradually weaker or quieter.",
    "drift apart": "To slowly lose closeness in a relationship.",
    "drive up": "To arrive in a vehicle; to make a price rise.",
    "end up": "To finish in a situation you did not plan.",
    "fade away": "To disappear slowly.",
    "fall apart": "To break into pieces; to lose emotional control.",
    "fall back": "To retreat; to return to an older habit.",
    "fall down": "To drop to the ground; to fail.",
    "fall for": "To fall in love with; to be tricked by.",
    "fall out": "To quarrel and stop being friends.",
    "figure out": "To understand after thinking; to solve.",
    "fill up": "To make something completely full.",
    "find out": "To discover a fact.",
    "freak out": "To panic or react with extreme emotion.",
    "get along": "To have a good relationship with someone.",
    "get away": "To escape.",
    "get back": "To return; to recover something lost.",
    "get by": "To survive with just enough money or skill.",
    "get down": "To lower yourself; to dance and enjoy yourself.",
    "get in": "To enter (a car, a place).",
    "get off": "To leave a vehicle; to stop touching something.",
    "get on": "To board a vehicle; to have a good relationship (UK).",
    "get out": "To leave; to escape.",
    "get over": "To recover from an illness, a shock or a breakup.",
    "get through": "To survive a difficult period; to make contact.",
    "get up": "To rise from bed or from a seat.",
    "give away": "To donate; to reveal a secret.",
    "give back": "To return something to its owner.",
    "give in": "To stop resisting; to yield.",
    "give out": "To distribute; to stop functioning.",
    "give up": "To stop trying; to surrender; to quit a habit.",
    "go away": "To leave; to disappear.",
    "go back": "To return.",
    "go down": "To descend; to be recorded in history.",
    "go for": "To choose; to attack or pursue.",
    "go off": "To explode or ring; to leave suddenly.",
    "go on": "To continue; to happen.",
    "go out": "To leave home for entertainment; to date someone.",
    "go through": "To endure a difficult experience; to examine carefully.",
    "go up": "To increase; to rise.",
    "grow up": "To become an adult; to behave maturely.",
    "hang around": "To stay in a place doing nothing in particular.",
    "hang on": "To wait; to hold tightly.",
    "hang out": "To spend relaxed time with people.",
    "hang up": "To end a phone call.",
    "hold back": "To restrain a feeling; to prevent progress.",
    "hold on": "To wait; to grip something firmly.",
    "hold out": "To resist; to extend your hand.",
    "hold up": "To delay; to support; to rob.",
    "hurry up": "To move faster.",
    "keep on": "To continue doing something.",
    "keep up": "To maintain the same pace or standard.",
    "kick off": "To begin (an event).",
    "knock down": "To hit something so it falls.",
    "knock out": "To make unconscious; to eliminate.",
    "lay down": "To put something on a surface; to state a rule.",
    "let down": "To disappoint someone who trusted you.",
    "let go": "To release; to stop holding on emotionally.",
    "let in": "To allow to enter.",
    "let out": "To release; to make a sound escape.",
    "let up": "To become less intense.",
    "light up": "To illuminate; to become visibly happy.",
    "live on": "To continue to exist; to survive on something.",
    "look after": "To take care of someone or something.",
    "look around": "To examine your surroundings.",
    "look back": "To think about the past.",
    "look down": "To lower your eyes; (look down on) to despise.",
    "look for": "To search for.",
    "look into": "To investigate.",
    "look out": "Be careful! / to watch for danger.",
    "look up": "To search for information; to improve.",
    "make out": "To manage; to distinguish; to kiss passionately.",
    "make up": "To invent a story; to reconcile after a fight.",
    "mess up": "To do something badly; to ruin something.",
    "move on": "To stop dwelling on the past and continue with life.",
    "move out": "To leave a home permanently.",
    "open up": "To share your feelings honestly; to unlock.",
    "pass by": "To move past; (of time) to elapse.",
    "pass out": "To faint; to distribute.",
    "pay back": "To return money; to take revenge.",
    "pay off": "To finish paying a debt; to produce a good result.",
    "pick out": "To choose; to distinguish from a group.",
    "pick up": "To lift; to collect someone; to learn casually.",
    "pull off": "To succeed at something difficult.",
    "pull over": "To move a vehicle to the side of the road.",
    "pull through": "To survive a crisis or an illness.",
    "pull up": "To stop a vehicle; to arrive.",
    "push away": "To reject someone emotionally.",
    "put down": "To place on a surface; to insult someone.",
    "put off": "To postpone; to cause dislike.",
    "put on": "To dress in; to pretend.",
    "put out": "To extinguish; to publish or release.",
    "put up": "To build or display; (put up with) to tolerate.",
    "reach out": "To ask for help or to offer contact.",
    "ride out": "To survive a difficult period without giving up.",
    "rise up": "To stand; to rebel.",
    "roll over": "To turn while lying down; to surrender easily.",
    "run away": "To escape; to leave home secretly.",
    "run into": "To meet by chance; to collide with.",
    "run out": "To have no more of something.",
    "run over": "To hit with a vehicle; to review quickly.",
    "screw up": "To make a serious mistake.",
    "sell out": "To sell everything; to betray your principles for money.",
    "set off": "To start a journey; to trigger.",
    "set up": "To arrange or establish; to trap someone.",
    "settle down": "To become calm; to start a stable life.",
    "show off": "To display something to impress people.",
    "show up": "To arrive, often unexpectedly or late.",
    "shut down": "To close or stop completely.",
    "shut up": "To stop talking (rude).",
    "sing along": "To sing at the same time as a recording or a singer.",
    "sit down": "To take a seat.",
    "slip away": "To leave quietly; to be lost gradually.",
    "slow down": "To reduce speed or intensity.",
    "speed up": "To go faster.",
    "stand by": "To support someone loyally; to wait ready.",
    "stand out": "To be noticeably different or better.",
    "stand up": "To rise to your feet; to fail to meet a date.",
    "start over": "To begin again from zero.",
    "stay up": "To remain awake late.",
    "step back": "To move away in order to reconsider.",
    "step up": "To take responsibility; to improve your effort.",
    "stick around": "To stay in a place or a relationship.",
    "stick together": "To stay loyal to one another.",
    "stop by": "To visit briefly.",
    "take back": "To retract words; to return an item.",
    "take in": "To absorb information; to give shelter; to deceive.",
    "take off": "To leave the ground; to remove clothing; to succeed fast.",
    "take out": "To remove; to invite someone on a date.",
    "take over": "To assume control.",
    "take up": "To start a new activity; to occupy space or time.",
    "tear apart": "To destroy; to cause deep emotional pain.",
    "tear up": "To rip into pieces; to begin to cry.",
    "think over": "To consider carefully before deciding.",
    "throw away": "To discard; to waste an opportunity.",
    "tie down": "To restrict someone's freedom.",
    "try out": "To test something.",
    "turn around": "To rotate; to reverse a bad situation.",
    "turn back": "To return the way you came.",
    "turn down": "To reject an offer; to lower the volume.",
    "turn into": "To transform into something else.",
    "turn off": "To stop a device; to make someone lose interest.",
    "turn on": "To start a device; to excite someone.",
    "turn out": "To end in a particular way; to prove to be.",
    "turn up": "To arrive; to increase the volume.",
    "wait up": "To stay awake waiting; to wait for someone to catch up.",
    "wake up": "To stop sleeping; to become aware.",
    "walk away": "To leave a situation, refusing to deal with it.",
    "walk out": "To leave angrily; to abandon someone.",
    "wash away": "To remove by water; to make guilt disappear.",
    "watch out": "Be careful!",
    "wear out": "To use until damaged; to exhaust someone.",
    "wind up": "To end up somewhere; to annoy someone.",
    "wipe out": "To destroy completely; to exhaust.",
    "work out": "To exercise; to solve; to end well.",
    "write down": "To record in writing.",
}

# ==========================================================================
# 4. IDIOMS
#    Figurative expressions whose meaning cannot be deduced word by word.
#    Phrases containing "my" are automatically expanded by the engine to
#    your / his / her / their / our / its, so "broke her heart" also matches.
# ==========================================================================
IDIOMS = {
    "break my heart": "To cause someone deep emotional pain.",
    "broken heart": "The state of deep sadness after losing love.",
    "heart of gold": "A very kind and generous nature.",
    "heart of stone": "An unfeeling, merciless nature.",
    "wear my heart on my sleeve": "To show your emotions openly.",
    "head over heels": "Completely and helplessly in love.",
    "over the moon": "Extremely happy.",
    "on cloud nine": "In a state of perfect happiness.",
    "down in the dumps": "Sad and without energy.",
    "under the weather": "Slightly ill.",
    "under my skin": "Irritating you, or occupying your thoughts obsessively.",
    "cold feet": "Sudden fear before an important commitment.",
    "cost an arm and a leg": "To be extremely expensive.",
    "piece of cake": "Something very easy.",
    "hit the road": "To leave / start a journey.",
    "hit the hay": "To go to bed.",
    "hit the sack": "To go to bed.",
    "call it a day": "To stop working for now.",
    "call it quits": "To end something, often a relationship.",
    "let the cat out of the bag": "To reveal a secret by accident.",
    "once in a blue moon": "Very rarely.",
    "out of the blue": "Completely unexpectedly.",
    "burn bridges": "To destroy relationships you may need later.",
    "bite the dust": "To fail, to die, or to be destroyed.",
    "bite my tongue": "To stop yourself from saying something.",
    "kick the bucket": "To die (humorous).",
    "spill the beans": "To reveal secret information.",
    "sit tight": "To wait patiently without acting.",
    "back to square one": "Back to the very beginning after a failure.",
    "the last straw": "The final small problem that makes you give up.",
    "second to none": "Better than everything else.",
    "in the same boat": "In the same difficult situation as others.",
    "no strings attached": "Without conditions or obligations.",
    "play with fire": "To take a dangerous risk.",
    "walk on eggshells": "To act very carefully to avoid upsetting someone.",
    "beat around the bush": "To avoid saying what you really mean.",
    "blow off steam": "To release anger or stress harmlessly.",
    "cut to the chase": "To get to the important point immediately.",
    "cold shoulder": "Deliberate unfriendliness or rejection.",
    "green with envy": "Extremely jealous.",
    "in hot water": "In serious trouble.",
    "keep an eye on": "To watch carefully.",
    "lose my mind": "To become extremely stressed or irrational.",
    "make ends meet": "To earn just enough money to survive.",
    "miss the boat": "To lose an opportunity by being too slow.",
    "on thin ice": "In a risky situation where one mistake is fatal.",
    "pull my leg": "To tease someone with a joke.",
    "rain on my parade": "To spoil someone's happy moment.",
    "raining cats and dogs": "Raining very heavily.",
    "ride or die": "Someone loyal to you no matter what happens.",
    "see eye to eye": "To agree completely.",
    "steal the show": "To attract all the attention.",
    "take it easy": "To relax; to not work too hard.",
    "tip of the iceberg": "A small visible part of a much bigger problem.",
    "through thick and thin": "Through good times and bad times.",
    "time flies": "Time passes surprisingly quickly.",
    "up in the air": "Undecided and uncertain.",
    "wild goose chase": "A hopeless search that wastes time.",
    "blessing in disguise": "Something bad that turns out to be good.",
    "add fuel to the fire": "To make a bad situation worse.",
    "against all odds": "Despite very little chance of success.",
    "all ears": "Listening with full attention.",
    "at the drop of a hat": "Immediately, without hesitation.",
    "back on my feet": "Recovered after an illness or a hard period.",
    "better late than never": "Doing it late is better than not at all.",
    "bury the hatchet": "To make peace after a conflict.",
    "by the skin of my teeth": "Only just; barely succeeding.",
    "cry over spilled milk": "To regret something that cannot be changed.",
    "down to earth": "Practical, modest and realistic.",
    "easier said than done": "Simple to suggest but hard to do.",
    "face the music": "To accept the consequences of your actions.",
    "fall from grace": "To lose respect or status after a mistake.",
    "fish out of water": "Someone uncomfortable in a new environment.",
    "get the hang of": "To learn how to do something with practice.",
    "give it a shot": "To try something.",
    "go the extra mile": "To make more effort than expected.",
    "hang in there": "Stay strong and do not give up.",
    "hit the nail on the head": "To describe something exactly right.",
    "hold your horses": "Wait; slow down.",
    "in the long run": "Over an extended period of time.",
    "it takes two to tango": "Both people share responsibility.",
    "jump the gun": "To act too soon.",
    "keep your chin up": "Stay positive in a hard moment.",
    "kill two birds with one stone": "To solve two problems with one action.",
    "last but not least": "Mentioned last but equally important.",
    "let bygones be bygones": "To forgive and forget the past.",
    "light at the end of the tunnel": "A sign that a hard period will end.",
    "long story short": "To summarise quickly.",
    "lose track of time": "To not notice how much time has passed.",
    "no pain no gain": "Success requires effort and suffering.",
    "off the hook": "Free from blame or obligation.",
    "on the same page": "In agreement / sharing the same understanding.",
    "once upon a time": "Long ago (traditional story opening).",
    "over my dead body": "Absolutely never, I will resist completely.",
    "pick up the pieces": "To recover order after a disaster.",
    "play it by ear": "To improvise instead of planning.",
    "put yourself in my shoes": "To imagine another person's situation.",
    "read between the lines": "To understand the hidden meaning.",
    "rock the boat": "To disturb a stable situation.",
    "run out of time": "To have no time left.",
    "set in stone": "Permanent and impossible to change.",
    "so far so good": "Everything is fine up to this point.",
    "speak of the devil": "Said when the person you mentioned appears.",
    "take with a grain of salt": "To not believe something completely.",
    "turn a blind eye": "To deliberately ignore wrongdoing.",
    "when pigs fly": "Never; something impossible.",
    "the world is your oyster": "You can achieve anything you want.",
    "burn the midnight oil": "To work or stay awake very late.",
    "chase rainbows": "To pursue an unrealistic dream.",
    "close but no cigar": "Almost successful, but not quite.",
    "dead of night": "The darkest, quietest part of the night.",
    "fall head first": "To commit to something completely and impulsively.",
    "for good": "Permanently, forever.",
    "hold on tight": "To keep going and resist letting go.",
    "in the blink of an eye": "Extremely fast.",
    "lose my head": "To stop thinking rationally because of emotion.",
    "made for each other": "Perfectly compatible as a couple.",
    "on the run": "Escaping, especially from the police.",
    "out of my league": "Too good or too attractive for you.",
    "part ways": "To separate and go in different directions.",
    "second chance": "Another opportunity after a failure.",
    "set the record straight": "To correct a false story.",
    "sink or swim": "To fail or succeed with no help.",
    "stand the test of time": "To remain good or valid for many years.",
    "take a toll": "To cause gradual damage or exhaustion.",
    "the calm before the storm": "A quiet period before serious trouble.",
    "turn the page": "To move on to a new chapter of life.",
    "walk a fine line": "To balance between two risky extremes.",
    "wear thin": "To become less acceptable or less amusing over time.",
}

# ==========================================================================
# 5. SLANG
#    Informal vocabulary. Mostly single words, so lemma matching handles
#    plurals automatically (vibes -> vibe).
# ==========================================================================
SLANG = {
    "so blue": "feeling very sad or depressed",
    "blue": "sad or depressed (when describing a feeling)",
    "lit": "exciting, excellent, full of energy",
    "flex": "to show off wealth or success",
    "ghost": "to disappear and stop replying to someone",
    "cap": "a lie",
    "no cap": "no lie / I am being honest",
    "vibes": "the emotional atmosphere of a place or person",
    "catch feelings": "to start falling in love unexpectedly",
    "salty": "bitter or resentful about something",
    "savage": "brutally direct, without caring about feelings",
    "throw shade": "to insult someone subtly",
    "shade": "a subtle insult",
    "slay": "to do something impressively well",
    "bae": "boyfriend or girlfriend ('before anyone else')",
    "boo": "an affectionate name for a partner",
    "hustle": "to work relentlessly to earn money",
    "chill": "relaxed / to relax",
    "dope": "excellent, very good",
    "sick": "excellent (informal, opposite of the literal sense)",
    "wasted": "very drunk",
    "turnt": "excited and partying hard",
    "drip": "very stylish clothing",
    "fire": "excellent, outstanding",
    "goat": "greatest of all time",
    "stan": "an obsessive fan / to be an obsessive fan",
    "sus": "suspicious",
    "tea": "gossip",
    "spill the tea": "to share gossip",
    "thirsty": "desperate for attention or affection",
    "woke": "socially and politically aware",
    "bougie": "pretending to be rich or sophisticated",
    "clout": "influence or fame",
    "low-key": "quietly, secretly, a little bit",
    "high-key": "openly, obviously, very much",
    "fam": "close friends treated like family",
    "squad": "your close group of friends",
    "homie": "a close friend",
    "crib": "home / house",
    "whip": "a car",
    "grind": "constant hard work",
    "glow up": "a dramatic improvement in appearance or confidence",
    "hooked": "addicted to or obsessed with something",
    "crush": "a romantic attraction to someone",
    "broke": "having no money",
    "bucks": "dollars / money",
    "mad": "very (as an intensifier) / angry",
    "hit different": "to feel unusually powerful or emotional",
    "living rent free": "occupying your thoughts constantly",
    "main character": "the person everything revolves around",
    "red flag": "a warning sign in a relationship",
    "shot": "an attempt / a small strong drink",
    "buzz": "a feeling of excitement or mild intoxication",
    "creep": "an unpleasant person who behaves strangely",
    "player": "someone who dates many people dishonestly",
    "hang": "to spend time together",
    "hood": "neighbourhood",
    "kick it": "to relax and spend time with someone",
    "trip": "an intense experience / to become upset",
    "wreck": "someone in a terrible emotional state",
    "hype": "excited enthusiasm, often exaggerated",
    "roll deep": "to move around with a large loyal group",
    "solid": "reliable and trustworthy",
    "shady": "dishonest or suspicious",
    "sweet talk": "flattering words used to persuade someone",
    "party animal": "someone who loves going out constantly",
    "night owl": "someone who stays awake late at night",
}

# ==========================================================================
# 6. PRESENTATION
# ==========================================================================
CATEGORY_ORDER = ["Contraction", "Reduced Form", "Phrasal Verb", "Idiom", "Slang"]

# Chosen to stay readable on the dark lyrics panel (black text on pastel).
CATEGORY_COLORS = {
    "Contraction": "#8ed3f0",
    "Reduced Form": "#c9b6f2",
    "Phrasal Verb": "#ffb0a8",
    "Idiom": "#a5e6a1",
    "Slang": "#ffd97d",
}

CATEGORY_HELP = {
    "Contraction": "Standard written English. Safe to use in an essay.",
    "Reduced Form": "Spoken / informal spelling. Understand it, but avoid writing it.",
    "Phrasal Verb": "Verb + particle. The particle changes the meaning completely.",
    "Idiom": "Fixed figurative expression. Do not translate word by word.",
    "Slang": "Informal vocabulary, often generational or regional.",
}
